language: racket

env:
 - RACKET_VERSION=6.0.1
 - RACKET_VERSION=6.1
 - RACKET_VERSION=6.1.1
 - RACKET_VERSION=HEAD

before_install:
- cd ..
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash # pipe to bash not sh!

install:

before_script:

script:
 - /usr/racket/bin/raco pkg install --deps search-auto --link measures-with-dimensions
 - /usr/racket/bin/raco test -x -p measures-with-dimensions

after_script:
